# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Run Anthos health check
  hosts: all
  environment:
    USE_GKE_GCLOUD_AUTH_PLUGIN: "true"
    HELM_EXPERIMENTAL_OCI: "1"
  vars:
    admin_cluster_kubeconfig: /home/ubuntu/kubeconfig
    anthos_log_name: anthos-monitoring-logs
    seesaw_log_name: seesaw-monitoring-logs
    project_id: apigee-hybrid-378710
  tags:
    - anthos-hc
  roles:
    - role: list-user-clusters
      tags: ['anthos-ls']
      environment:
        KUBECONFIG: '{{ admin_cluster_kubeconfig }}'
    # - role: anthos-clusters-diagnostics
    #   tags: ['anthos-diag']
    #   environment:
    #     KUBECONFIG: '{{ admin_cluster_kubeconfig }}'
    # - role: seesaw-health-check
    #   vars:
    #     operation: 'get seesawgroups'
    #   tags: ['seesaw']
    #   environment:
    #     KUBECONFIG: '{{ admin_cluster_kubeconfig }}'
