# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
# tasks file for seesaw-health-check
  - include_role: { name: get-user-cluster-kubeconfig }
    vars:
      usercluster_name: '{{ item.name}}'
      kubeconfig_file: '/tmp/{{ item.name }}.yaml'

  - include_role: { name: get-seesaw-info }
    vars: 
      kubeconfig_file: '/tmp/{{ item.name }}.yaml'

  - include_role: { name: gcloud-write-log }
    vars:
      log_severity: INFO
      log_message: '{{ seesaw_log_msg }}'
      payload_type: 'text'
      log_name: '{{ seesaw_log_name}}'
    tags: ['seesaw']
    when: all_ready == true

  - include_role: { name: gcloud-write-log }
    vars:
      log_severity: ERROR
      log_message: '{{ seesaw_log_msg }}'
      payload_type: 'text'
      log_name: '{{ seesaw_log_name}}'
    tags: ['seesaw']
    when: all_ready == false
